#测试环境配置
server:
  #端口
  port: 8082
spring:
  profiles: test
  #数据源
  datasource:
    url: jdbc:mysql://172.19.9.223:3306/good_manage?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: ${password}
  #thymeleaf模版
  thymeleaf:
    cache: true
#日志
logging:
  config: classpath:logback-jk.xml
  path: log

#数据库密码加密
#java -cp druid-1.1.0.jar com.alibaba.druid.filter.config.ConfigTools 你的密码
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALIIrhv6tAq+LO/ZYcVqsFdw5ZN67H9xYrsqhxIyexoeCcnrw7b9PaSShq94qj1if0aRrDgkCDCCkCrfhobZaqMCAwEAAQ==
password: F7AJqYN2NptXHZhFrBpLcpiHpqnyIITBY59qxc/5T6XuU4COC3x+qT+kpgyuzS4g2sZ3Oxu737nRboTwA9YeUw==

#上传文件配置信息
#文件仓库地址
repositoryPath: /home/good
#图片访问路径
imageUrl: http://image.good.com
#文档访问路径
docUrl: http://doc.good.com
